### ISSUE TITLE
Open treasure chest cause player can't join server

### ISSUE THREAD

**Issue by senlin114514** [Scouter456/Oceans_Delight#7]
My server install this mod,but it's have a bug
when some player open a treasure chest,player will have a error and can't join my server again.
This mistake isn't happen before my install this mod.
Here is the result:
![image](https://github.com/Scouter456/Oceans_Delight/assets/99373997/1d53e3be-dac2-45af-b427-9da2e90142a5)

**Comment by Scouter456** [comment]
You will have to send me the debug.log txt file a screenshot is not useful
