### ISSUE TITLE
Weird stray pixel on the guardian texture

### ISSUE THREAD

**Issue by Chris6ix** [Scouter456/Oceans_Delight#8]
The item `oceansdelight:guardian` has a single "transparent" pixel that was likely placed on accident. When holding the Item, the pixel is pretty much invisible when looking at the ground, for example, but when looking at the sky it is very noticeable. Here are 2 screenshots to show what i mean:
![2024-03-15_00 55 50](https://github.com/Scouter456/Oceans_Delight/assets/65610536/eb334dc5-4c52-423b-9c56-936d5bf01b5c)
![2024-03-15_00 56 46](https://github.com/Scouter456/Oceans_Delight/assets/65610536/9063fc0e-e487-4fc5-b035-7075fc4c20bc)

**Comment by Scouter456** [comment]
Thanks for the report I believe I fixed it if not do tell
